defaults:
  - scope:
      path: "https://gjdev-org.github.io/p1/assets/images"
    values:
      image: true
      sass:

style: compressed

exclude:
- package.json
- package-lock.json
- node_modules
- gulpfile.js
- assets/vendor
- README.md
- LICENSE

compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
